# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comp.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Compition_2(object):
    def setupUi(self, Compition_2):
        Compition_2.setObjectName("Compition_2")
        Compition_2.resize(1100, 600)
        Compition_2.setStyleSheet("background-color : #2d2d2d;\n"
"color : #b5b5b5\n"
"")
        self.Compition = QtWidgets.QWidget(Compition_2)
        self.Compition.setEnabled(True)
        self.Compition.setGeometry(QtCore.QRect(0, 0, 1101, 601))
        self.Compition.setStyleSheet("")
        self.Compition.setObjectName("Compition")
        self.labelCom = QtWidgets.QLabel(self.Compition)
        self.labelCom.setGeometry(QtCore.QRect(75, 40, 561, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(36)
        self.labelCom.setFont(font)
        self.labelCom.setObjectName("labelCom")
        self.btnRetourCom = QtWidgets.QToolButton(self.Compition)
        self.btnRetourCom.setGeometry(QtCore.QRect(20, 550, 41, 30))
        self.btnRetourCom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRetourCom.setStyleSheet("border:none")
        self.btnRetourCom.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/retour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRetourCom.setIcon(icon)
        self.btnRetourCom.setIconSize(QtCore.QSize(30, 30))
        self.btnRetourCom.setObjectName("btnRetourCom")
        self.label_194 = QtWidgets.QLabel(self.Compition)
        self.label_194.setGeometry(QtCore.QRect(25, 40, 40, 40))
        self.label_194.setText("")
        self.label_194.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/award.png"))
        self.label_194.setScaledContents(True)
        self.label_194.setObjectName("label_194")
        self.AjoutComp = QtWidgets.QWidget(self.Compition)
        self.AjoutComp.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.AjoutComp.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.AjoutComp.setObjectName("AjoutComp")
        self.ajouterComp = QtWidgets.QWidget(self.AjoutComp)
        self.ajouterComp.setGeometry(QtCore.QRect(220, 80, 681, 461))
        self.ajouterComp.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.ajouterComp.setObjectName("ajouterComp")
        self.NouvComp = QtWidgets.QLabel(self.ajouterComp)
        self.NouvComp.setGeometry(QtCore.QRect(50, 20, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.NouvComp.setFont(font)
        self.NouvComp.setObjectName("NouvComp")
        self.label_196 = QtWidgets.QLabel(self.ajouterComp)
        self.label_196.setGeometry(QtCore.QRect(13, 16, 31, 31))
        self.label_196.setText("")
        self.label_196.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/add.png"))
        self.label_196.setScaledContents(True)
        self.label_196.setObjectName("label_196")
        self.label_197 = QtWidgets.QLabel(self.ajouterComp)
        self.label_197.setGeometry(QtCore.QRect(290, 130, 31, 16))
        self.label_197.setObjectName("label_197")
        self.ajouNomComp = QtWidgets.QLineEdit(self.ajouterComp)
        self.ajouNomComp.setGeometry(QtCore.QRect(292, 150, 291, 31))
        self.ajouNomComp.setStyleSheet("border:1px solid gray")
        self.ajouNomComp.setObjectName("ajouNomComp")
        self.label_198 = QtWidgets.QLabel(self.ajouterComp)
        self.label_198.setGeometry(QtCore.QRect(290, 70, 31, 16))
        self.label_198.setObjectName("label_198")
        self.ajouIdCom = QtWidgets.QLineEdit(self.ajouterComp)
        self.ajouIdCom.setGeometry(QtCore.QRect(292, 90, 291, 31))
        self.ajouIdCom.setStyleSheet("border:1px solid gray")
        self.ajouIdCom.setText("")
        self.ajouIdCom.setObjectName("ajouIdCom")
        self.ajouDateFinComp = QtWidgets.QDateEdit(self.ajouterComp)
        self.ajouDateFinComp.setGeometry(QtCore.QRect(290, 270, 121, 31))
        self.ajouDateFinComp.setStyleSheet("border:1px solid gray")
        self.ajouDateFinComp.setCalendarPopup(True)
        self.ajouDateFinComp.setObjectName("ajouDateFinComp")
        self.label_203 = QtWidgets.QLabel(self.ajouterComp)
        self.label_203.setGeometry(QtCore.QRect(290, 250, 61, 16))
        self.label_203.setObjectName("label_203")
        self.label_204 = QtWidgets.QLabel(self.ajouterComp)
        self.label_204.setGeometry(QtCore.QRect(290, 190, 71, 16))
        self.label_204.setObjectName("label_204")
        self.ajouDateDebComp = QtWidgets.QDateEdit(self.ajouterComp)
        self.ajouDateDebComp.setGeometry(QtCore.QRect(290, 210, 121, 31))
        self.ajouDateDebComp.setStyleSheet("border:1px solid gray")
        self.ajouDateDebComp.setCalendarPopup(True)
        self.ajouDateDebComp.setObjectName("ajouDateDebComp")
        self.ajoutPhotoComp = QtWidgets.QLabel(self.ajouterComp)
        self.ajoutPhotoComp.setGeometry(QtCore.QRect(90, 80, 151, 161))
        self.ajoutPhotoComp.setText("")
        self.ajoutPhotoComp.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/user.png"))
        self.ajoutPhotoComp.setScaledContents(True)
        self.ajoutPhotoComp.setObjectName("ajoutPhotoComp")
        self.btnUplodComp = QtWidgets.QToolButton(self.ajouterComp)
        self.btnUplodComp.setGeometry(QtCore.QRect(120, 250, 111, 21))
        self.btnUplodComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUplodComp.setIcon(icon1)
        self.btnUplodComp.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnUplodComp.setObjectName("btnUplodComp")
        self.label_217 = QtWidgets.QLabel(self.ajouterComp)
        self.label_217.setGeometry(QtCore.QRect(300, 310, 71, 16))
        self.label_217.setObjectName("label_217")
        self.widgetAjoutPrix = QtWidgets.QWidget(self.ajouterComp)
        self.widgetAjoutPrix.setGeometry(QtCore.QRect(290, 320, 311, 81))
        self.widgetAjoutPrix.setStyleSheet("border : 1px solid rgb(255, 255, 255);\n"
"border-radius:2px\n"
"")
        self.widgetAjoutPrix.setObjectName("widgetAjoutPrix")
        self.ajouPrixPrem = QtWidgets.QLineEdit(self.widgetAjoutPrix)
        self.ajouPrixPrem.setGeometry(QtCore.QRect(50, 40, 61, 31))
        self.ajouPrixPrem.setStyleSheet("border:1px solid gray")
        self.ajouPrixPrem.setPlaceholderText("")
        self.ajouPrixPrem.setObjectName("ajouPrixPrem")
        self.label_199 = QtWidgets.QLabel(self.widgetAjoutPrix)
        self.label_199.setGeometry(QtCore.QRect(60, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_199.setFont(font)
        self.label_199.setStyleSheet("border : 0px ;")
        self.label_199.setObjectName("label_199")
        self.label_200 = QtWidgets.QLabel(self.widgetAjoutPrix)
        self.label_200.setGeometry(QtCore.QRect(140, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_200.setFont(font)
        self.label_200.setStyleSheet("border : 0px ;")
        self.label_200.setObjectName("label_200")
        self.ajouPrixDeux = QtWidgets.QLineEdit(self.widgetAjoutPrix)
        self.ajouPrixDeux.setGeometry(QtCore.QRect(130, 40, 61, 31))
        self.ajouPrixDeux.setStyleSheet("border:1px solid gray")
        self.ajouPrixDeux.setObjectName("ajouPrixDeux")
        self.label_201 = QtWidgets.QLabel(self.widgetAjoutPrix)
        self.label_201.setGeometry(QtCore.QRect(220, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_201.setFont(font)
        self.label_201.setStyleSheet("border : 0px ;")
        self.label_201.setObjectName("label_201")
        self.ajouPrixTrois = QtWidgets.QLineEdit(self.widgetAjoutPrix)
        self.ajouPrixTrois.setGeometry(QtCore.QRect(210, 40, 61, 31))
        self.ajouPrixTrois.setStyleSheet("border:1px solid gray")
        self.ajouPrixTrois.setObjectName("ajouPrixTrois")
        self.btnEnregComp = QtWidgets.QToolButton(self.ajouterComp)
        self.btnEnregComp.setGeometry(QtCore.QRect(590, 420, 31, 31))
        self.btnEnregComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEnregComp.setIcon(icon2)
        self.btnEnregComp.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregComp.setObjectName("btnEnregComp")
        self.btnAnnuleComp = QtWidgets.QToolButton(self.ajouterComp)
        self.btnAnnuleComp.setGeometry(QtCore.QRect(630, 420, 31, 31))
        self.btnAnnuleComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnnuleComp.setIcon(icon3)
        self.btnAnnuleComp.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnuleComp.setObjectName("btnAnnuleComp")
        self.NouvComp.raise_()
        self.label_196.raise_()
        self.label_197.raise_()
        self.ajouNomComp.raise_()
        self.label_198.raise_()
        self.ajouIdCom.raise_()
        self.ajouDateFinComp.raise_()
        self.label_203.raise_()
        self.label_204.raise_()
        self.ajouDateDebComp.raise_()
        self.ajoutPhotoComp.raise_()
        self.btnUplodComp.raise_()
        self.widgetAjoutPrix.raise_()
        self.label_217.raise_()
        self.btnEnregComp.raise_()
        self.btnAnnuleComp.raise_()
        self.ModifComp = QtWidgets.QWidget(self.Compition)
        self.ModifComp.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.ModifComp.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.ModifComp.setObjectName("ModifComp")
        self.modifComp = QtWidgets.QWidget(self.ModifComp)
        self.modifComp.setGeometry(QtCore.QRect(220, 80, 681, 461))
        self.modifComp.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.modifComp.setObjectName("modifComp")
        self.ModifCompLabel = QtWidgets.QLabel(self.modifComp)
        self.ModifCompLabel.setGeometry(QtCore.QRect(50, 20, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.ModifCompLabel.setFont(font)
        self.ModifCompLabel.setObjectName("ModifCompLabel")
        self.label_206 = QtWidgets.QLabel(self.modifComp)
        self.label_206.setGeometry(QtCore.QRect(13, 16, 31, 31))
        self.label_206.setText("")
        self.label_206.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/modif.png"))
        self.label_206.setScaledContents(True)
        self.label_206.setObjectName("label_206")
        self.label_207 = QtWidgets.QLabel(self.modifComp)
        self.label_207.setGeometry(QtCore.QRect(290, 130, 41, 16))
        self.label_207.setObjectName("label_207")
        self.modifNomComp = QtWidgets.QLineEdit(self.modifComp)
        self.modifNomComp.setGeometry(QtCore.QRect(292, 150, 291, 31))
        self.modifNomComp.setStyleSheet("border:1px solid gray")
        self.modifNomComp.setObjectName("modifNomComp")
        self.label_208 = QtWidgets.QLabel(self.modifComp)
        self.label_208.setGeometry(QtCore.QRect(290, 70, 31, 16))
        self.label_208.setObjectName("label_208")
        self.modifIdComp = QtWidgets.QLineEdit(self.modifComp)
        self.modifIdComp.setGeometry(QtCore.QRect(292, 90, 291, 31))
        self.modifIdComp.setStyleSheet("border:1px solid gray")
        self.modifIdComp.setObjectName("modifIdComp")
        self.modifDateFinComp = QtWidgets.QDateEdit(self.modifComp)
        self.modifDateFinComp.setGeometry(QtCore.QRect(290, 270, 121, 31))
        self.modifDateFinComp.setStyleSheet("border:1px solid gray")
        self.modifDateFinComp.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 17), QtCore.QTime(0, 0, 0)))
        self.modifDateFinComp.setCalendarPopup(True)
        self.modifDateFinComp.setObjectName("modifDateFinComp")
        self.label_213 = QtWidgets.QLabel(self.modifComp)
        self.label_213.setGeometry(QtCore.QRect(290, 250, 61, 16))
        self.label_213.setObjectName("label_213")
        self.modifPhotoCupComp = QtWidgets.QLabel(self.modifComp)
        self.modifPhotoCupComp.setGeometry(QtCore.QRect(90, 80, 151, 161))
        self.modifPhotoCupComp.setText("")
        self.modifPhotoCupComp.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/cup.png"))
        self.modifPhotoCupComp.setScaledContents(True)
        self.modifPhotoCupComp.setObjectName("modifPhotoCupComp")
        self.btnModifUplodComp = QtWidgets.QToolButton(self.modifComp)
        self.btnModifUplodComp.setGeometry(QtCore.QRect(120, 250, 111, 21))
        self.btnModifUplodComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModifUplodComp.setIcon(icon1)
        self.btnModifUplodComp.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnModifUplodComp.setObjectName("btnModifUplodComp")
        self.modifDateDebComp = QtWidgets.QDateEdit(self.modifComp)
        self.modifDateDebComp.setGeometry(QtCore.QRect(290, 210, 121, 31))
        self.modifDateDebComp.setStyleSheet("border:1px solid gray")
        self.modifDateDebComp.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 17), QtCore.QTime(0, 0, 0)))
        self.modifDateDebComp.setCalendarPopup(True)
        self.modifDateDebComp.setObjectName("modifDateDebComp")
        self.label_218 = QtWidgets.QLabel(self.modifComp)
        self.label_218.setGeometry(QtCore.QRect(290, 190, 71, 16))
        self.label_218.setObjectName("label_218")
        self.ModifDeuxPrix = QtWidgets.QLineEdit(self.modifComp)
        self.ModifDeuxPrix.setGeometry(QtCore.QRect(290, 360, 121, 21))
        self.ModifDeuxPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.ModifDeuxPrix.setObjectName("ModifDeuxPrix")
        self.ModifTroisPrix = QtWidgets.QLineEdit(self.modifComp)
        self.ModifTroisPrix.setGeometry(QtCore.QRect(510, 360, 131, 23))
        self.ModifTroisPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.ModifTroisPrix.setObjectName("ModifTroisPrix")
        self.cupPrix = QtWidgets.QLabel(self.modifComp)
        self.cupPrix.setGeometry(QtCore.QRect(330, 350, 251, 91))
        self.cupPrix.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.cupPrix.setText("")
        self.cupPrix.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/pdmm.png"))
        self.cupPrix.setScaledContents(True)
        self.cupPrix.setObjectName("cupPrix")
        self.ModifPremiPrix = QtWidgets.QLineEdit(self.modifComp)
        self.ModifPremiPrix.setGeometry(QtCore.QRect(410, 320, 121, 23))
        self.ModifPremiPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.ModifPremiPrix.setObjectName("ModifPremiPrix")
        self.btnEnregModifComp = QtWidgets.QToolButton(self.modifComp)
        self.btnEnregModifComp.setGeometry(QtCore.QRect(120, 400, 31, 31))
        self.btnEnregModifComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEnregModifComp.setIcon(icon2)
        self.btnEnregModifComp.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregModifComp.setObjectName("btnEnregModifComp")
        self.btnAnnuleModifComp = QtWidgets.QToolButton(self.modifComp)
        self.btnAnnuleModifComp.setGeometry(QtCore.QRect(160, 400, 31, 31))
        self.btnAnnuleModifComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAnnuleModifComp.setIcon(icon3)
        self.btnAnnuleModifComp.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnuleModifComp.setObjectName("btnAnnuleModifComp")
        self.ModifCompLabel.raise_()
        self.label_206.raise_()
        self.label_207.raise_()
        self.modifNomComp.raise_()
        self.label_208.raise_()
        self.modifIdComp.raise_()
        self.modifDateFinComp.raise_()
        self.label_213.raise_()
        self.modifPhotoCupComp.raise_()
        self.btnModifUplodComp.raise_()
        self.modifDateDebComp.raise_()
        self.label_218.raise_()
        self.cupPrix.raise_()
        self.ModifPremiPrix.raise_()
        self.ModifDeuxPrix.raise_()
        self.ModifTroisPrix.raise_()
        self.btnEnregModifComp.raise_()
        self.btnAnnuleModifComp.raise_()
        self.SupprimerComp = QtWidgets.QWidget(self.Compition)
        self.SupprimerComp.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.SupprimerComp.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.SupprimerComp.setObjectName("SupprimerComp")
        self.SuppComp = QtWidgets.QWidget(self.SupprimerComp)
        self.SuppComp.setGeometry(QtCore.QRect(-20, 240, 1131, 141))
        self.SuppComp.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.SuppComp.setObjectName("SuppComp")
        self.label_215 = QtWidgets.QLabel(self.SuppComp)
        self.label_215.setGeometry(QtCore.QRect(190, 40, 871, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.label_215.setFont(font)
        self.label_215.setObjectName("label_215")
        self.label_216 = QtWidgets.QLabel(self.SuppComp)
        self.label_216.setGeometry(QtCore.QRect(130, 46, 41, 41))
        self.label_216.setText("")
        self.label_216.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/supp.png"))
        self.label_216.setScaledContents(True)
        self.label_216.setObjectName("label_216")
        self.btnAnnulerSuppComp = QtWidgets.QToolButton(self.SuppComp)
        self.btnAnnulerSuppComp.setGeometry(QtCore.QRect(640, 100, 31, 31))
        self.btnAnnulerSuppComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAnnulerSuppComp.setIcon(icon3)
        self.btnAnnulerSuppComp.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnulerSuppComp.setObjectName("btnAnnulerSuppComp")
        self.btnEnregSuppComp = QtWidgets.QToolButton(self.SuppComp)
        self.btnEnregSuppComp.setGeometry(QtCore.QRect(600, 100, 31, 31))
        self.btnEnregSuppComp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEnregSuppComp.setIcon(icon2)
        self.btnEnregSuppComp.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregSuppComp.setObjectName("btnEnregSuppComp")
        self.listCompet = QtWidgets.QListWidget(self.Compition)
        self.listCompet.setGeometry(QtCore.QRect(30, 150, 431, 381))
        self.listCompet.setStyleSheet("\n"
"border : 1px groove;border-color:#b5b5b5;color:white ")
        self.listCompet.setObjectName("listCompet")
        self.label_68 = QtWidgets.QLabel(self.Compition)
        self.label_68.setGeometry(QtCore.QRect(434, 125, 20, 20))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/cherche.png"))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName("label_68")
        self.txtRechComp = QtWidgets.QLineEdit(self.Compition)
        self.txtRechComp.setGeometry(QtCore.QRect(30, 120, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtRechComp.setFont(font)
        self.txtRechComp.setStyleSheet("border : 1px groove;border-color:#b5b5b5;color:white")
        self.txtRechComp.setObjectName("txtRechComp")
        self.Prop = QtWidgets.QFrame(self.Compition)
        self.Prop.setGeometry(QtCore.QRect(590, 120, 451, 411))
        self.Prop.setStyleSheet("border : 1px groove;border-color:#b5b5b5;color:white")
        self.Prop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Prop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Prop.setObjectName("Prop")
        self.label_69 = QtWidgets.QLabel(self.Prop)
        self.label_69.setGeometry(QtCore.QRect(170, 70, 41, 21))
        self.label_69.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.Prop)
        self.label_70.setGeometry(QtCore.QRect(170, 100, 71, 21))
        self.label_70.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_70.setObjectName("label_70")
        self.datedebFiche = QtWidgets.QLineEdit(self.Prop)
        self.datedebFiche.setGeometry(QtCore.QRect(240, 100, 113, 23))
        self.datedebFiche.setObjectName("datedebFiche")
        self.label_71 = QtWidgets.QLabel(self.Prop)
        self.label_71.setGeometry(QtCore.QRect(170, 130, 61, 21))
        self.label_71.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_71.setObjectName("label_71")
        self.datefinFiche = QtWidgets.QLineEdit(self.Prop)
        self.datefinFiche.setGeometry(QtCore.QRect(240, 130, 113, 23))
        self.datefinFiche.setObjectName("datefinFiche")
        self.cup = QtWidgets.QLabel(self.Prop)
        self.cup.setGeometry(QtCore.QRect(60, 60, 71, 71))
        self.cup.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.cup.setText("")
        self.cup.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/cup.png"))
        self.cup.setScaledContents(True)
        self.cup.setObjectName("cup")
        self.cupClassement = QtWidgets.QLabel(self.Prop)
        self.cupClassement.setGeometry(QtCore.QRect(110, 240, 251, 91))
        self.cupClassement.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.cupClassement.setText("")
        self.cupClassement.setPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/pdmm.png"))
        self.cupClassement.setScaledContents(True)
        self.cupClassement.setObjectName("cupClassement")
        self.labelPremiPrix = QtWidgets.QLineEdit(self.Prop)
        self.labelPremiPrix.setGeometry(QtCore.QRect(190, 210, 121, 23))
        self.labelPremiPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.labelPremiPrix.setObjectName("labelPremiPrix")
        self.labelDeuxPrix = QtWidgets.QLineEdit(self.Prop)
        self.labelDeuxPrix.setGeometry(QtCore.QRect(70, 250, 121, 21))
        self.labelDeuxPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.labelDeuxPrix.setObjectName("labelDeuxPrix")
        self.labelTroiPrix = QtWidgets.QLineEdit(self.Prop)
        self.labelTroiPrix.setGeometry(QtCore.QRect(290, 250, 121, 23))
        self.labelTroiPrix.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.labelTroiPrix.setObjectName("labelTroiPrix")
        self.label_72 = QtWidgets.QLabel(self.Prop)
        self.label_72.setGeometry(QtCore.QRect(170, 40, 41, 21))
        self.label_72.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_72.setObjectName("label_72")
        self.IdCompFiche = QtWidgets.QLineEdit(self.Prop)
        self.IdCompFiche.setGeometry(QtCore.QRect(240, 40, 121, 23))
        self.IdCompFiche.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.IdCompFiche.setObjectName("IdCompFiche")
        self.NomCompFiche = QtWidgets.QLineEdit(self.Prop)
        self.NomCompFiche.setGeometry(QtCore.QRect(240, 70, 121, 23))
        self.NomCompFiche.setStyleSheet("QLineEdit{\n"
" border: 0px  tranparent;\n"
"}")
        self.NomCompFiche.setObjectName("NomCompFiche")
        self.btnModifEntre_3 = QtWidgets.QToolButton(self.Compition)
        self.btnModifEntre_3.setGeometry(QtCore.QRect(1600, 60, 31, 31))
        self.btnModifEntre_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModifEntre_3.setStyleSheet("border:none")
        self.btnModifEntre_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/modif.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModifEntre_3.setIcon(icon4)
        self.btnModifEntre_3.setIconSize(QtCore.QSize(30, 30))
        self.btnModifEntre_3.setObjectName("btnModifEntre_3")
        self.btnModifCom = QtWidgets.QToolButton(self.Compition)
        self.btnModifCom.setGeometry(QtCore.QRect(940, 45, 31, 31))
        self.btnModifCom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModifCom.setStyleSheet("border:none")
        self.btnModifCom.setText("")
        self.btnModifCom.setIcon(icon4)
        self.btnModifCom.setIconSize(QtCore.QSize(30, 30))
        self.btnModifCom.setObjectName("btnModifCom")
        self.btnAjoutCom = QtWidgets.QToolButton(self.Compition)
        self.btnAjoutCom.setGeometry(QtCore.QRect(890, 45, 31, 31))
        self.btnAjoutCom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAjoutCom.setStyleSheet("border:none")
        self.btnAjoutCom.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAjoutCom.setIcon(icon5)
        self.btnAjoutCom.setIconSize(QtCore.QSize(30, 30))
        self.btnAjoutCom.setObjectName("btnAjoutCom")
        self.btnSuppCom = QtWidgets.QToolButton(self.Compition)
        self.btnSuppCom.setGeometry(QtCore.QRect(990, 45, 31, 31))
        self.btnSuppCom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSuppCom.setStyleSheet("border:none")
        self.btnSuppCom.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/aymen/PycharmProjects/lone/tournamentPage/supp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuppCom.setIcon(icon6)
        self.btnSuppCom.setIconSize(QtCore.QSize(30, 30))
        self.btnSuppCom.setObjectName("btnSuppCom")
        self.label_157 = QtWidgets.QLabel(self.Compition)
        self.label_157.setGeometry(QtCore.QRect(610, 110, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(False)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.btnSuppCom.raise_()
        self.btnModifCom.raise_()
        self.btnAjoutCom.raise_()
        self.Prop.raise_()
        self.label_157.raise_()
        self.txtRechComp.raise_()
        self.label_68.raise_()
        self.listCompet.raise_()
        self.labelCom.raise_()
        self.btnRetourCom.raise_()
        self.label_194.raise_()
        self.ModifComp.raise_()
        self.SupprimerComp.raise_()
        self.btnModifEntre_3.raise_()
        self.AjoutComp.raise_()

        self.retranslateUi(Compition_2)
        QtCore.QMetaObject.connectSlotsByName(Compition_2)

    def retranslateUi(self, Compition_2):
        _translate = QtCore.QCoreApplication.translate
        Compition_2.setWindowTitle(_translate("Compition_2", "Form"))
        self.labelCom.setText(_translate("Compition_2", "Liste Des Compétitions"))
        self.NouvComp.setText(_translate("Compition_2", "Nouvelle Compétition"))
        self.label_197.setText(_translate("Compition_2", "Nom"))
        self.ajouNomComp.setPlaceholderText(_translate("Compition_2", "Ex : CAF"))
        self.label_198.setText(_translate("Compition_2", "ID"))
        self.ajouIdCom.setPlaceholderText(_translate("Compition_2", "Ex : 04826640"))
        self.label_203.setText(_translate("Compition_2", "Date Fin"))
        self.label_204.setText(_translate("Compition_2", "Date debut"))
        self.btnUplodComp.setText(_translate("Compition_2", " Upload photo"))
        self.label_217.setText(_translate("Compition_2", "    Prix"))
        self.label_199.setText(_translate("Compition_2", "<<1>>"))
        self.label_200.setText(_translate("Compition_2", "<<2>>"))
        self.label_201.setText(_translate("Compition_2", "<<3>>"))
        self.btnEnregComp.setText(_translate("Compition_2", "..."))
        self.btnAnnuleComp.setText(_translate("Compition_2", "..."))
        self.ModifCompLabel.setText(_translate("Compition_2", "Modifier Compétition"))
        self.label_207.setText(_translate("Compition_2", "Nom"))
        self.modifNomComp.setText(_translate("Compition_2", "CAF"))
        self.modifNomComp.setPlaceholderText(_translate("Compition_2", "Ex : Msekni"))
        self.label_208.setText(_translate("Compition_2", "ID"))
        self.modifIdComp.setText(_translate("Compition_2", "CAF2020"))
        self.modifIdComp.setPlaceholderText(_translate("Compition_2", "Ex : 04826640"))
        self.label_213.setText(_translate("Compition_2", "Date Fin"))
        self.btnModifUplodComp.setText(_translate("Compition_2", " Upload photo"))
        self.label_218.setText(_translate("Compition_2", "Date debut"))
        self.ModifDeuxPrix.setText(_translate("Compition_2", "1,5 millions USD"))
        self.ModifTroisPrix.setText(_translate("Compition_2", "800 000 USD"))
        self.ModifPremiPrix.setText(_translate("Compition_2", "2,5 millions USD"))
        self.btnEnregModifComp.setText(_translate("Compition_2", "..."))
        self.btnAnnuleModifComp.setText(_translate("Compition_2", "..."))
        self.label_215.setText(_translate("Compition_2", "Voulez vous vraiment supprimer cette compétition ?"))
        self.btnAnnulerSuppComp.setText(_translate("Compition_2", "..."))
        self.btnEnregSuppComp.setText(_translate("Compition_2", "..."))
        self.txtRechComp.setPlaceholderText(_translate("Compition_2", "Chercher par nom"))
        self.label_69.setText(_translate("Compition_2", "Nom :"))
        self.label_70.setText(_translate("Compition_2", "Date Deb :"))
        self.datedebFiche.setText(_translate("Compition_2", "09/01/2020"))
        self.label_71.setText(_translate("Compition_2", "Date Fin :"))
        self.datefinFiche.setText(_translate("Compition_2", "08/03/2020"))
        self.labelPremiPrix.setText(_translate("Compition_2", "2,5 millions USD"))
        self.labelDeuxPrix.setText(_translate("Compition_2", "1,5 millions USD"))
        self.labelTroiPrix.setText(_translate("Compition_2", "800 000 USD"))
        self.label_72.setText(_translate("Compition_2", "ID :"))
        self.IdCompFiche.setText(_translate("Compition_2", "CF2020"))
        self.NomCompFiche.setText(_translate("Compition_2", "Coupe d\'Afrique"))
        self.label_157.setText(_translate("Compition_2", "Fiche Compétition"))
