# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistique.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 600)
        Form.setStyleSheet("background-color : #2d2d2d;\n"
"color : #b5b5b5")
        self.Statistique = QtWidgets.QWidget(Form)
        self.Statistique.setEnabled(True)
        self.Statistique.setGeometry(QtCore.QRect(-10, -10, 1101, 601))
        self.Statistique.setStyleSheet("")
        self.Statistique.setObjectName("Statistique")
        self.labelStatistique = QtWidgets.QLabel(self.Statistique)
        self.labelStatistique.setGeometry(QtCore.QRect(75, 40, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        8
        font.setPointSize(36)
        self.labelStatistique.setFont(font)
        self.labelStatistique.setObjectName("labelStatistique")
        self.btnRetourStatic = QtWidgets.QToolButton(self.Statistique)
        self.btnRetourStatic.setGeometry(QtCore.QRect(20, 550, 41, 30))
        self.btnRetourStatic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRetourStatic.setStyleSheet("border:none")
        self.btnRetourStatic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("retour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRetourStatic.setIcon(icon)
        self.btnRetourStatic.setIconSize(QtCore.QSize(30, 30))
        self.btnRetourStatic.setObjectName("btnRetourStatic")
        self.label_263 = QtWidgets.QLabel(self.Statistique)
        self.label_263.setGeometry(QtCore.QRect(25, 40, 40, 40))
        self.label_263.setText("")
        self.label_263.setPixmap(QtGui.QPixmap("football-stats-graphic (1).png"))
        self.label_263.setScaledContents(True)
        self.label_263.setObjectName("label_263")
        self.widgetBut = QtWidgets.QWidget(self.Statistique)
        self.widgetBut.setGeometry(QtCore.QRect(40, 160, 311, 371))
        self.widgetBut.setStyleSheet("border : 1px solid rgb(255, 252, 249)")
        self.widgetBut.setObjectName("widgetBut")
        self.photoButtuer = QtWidgets.QLabel(self.widgetBut)
        self.photoButtuer.setGeometry(QtCore.QRect(60, 70, 161, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(19)
        self.photoButtuer.setFont(font)
        self.photoButtuer.setText("")
        self.photoButtuer.setPixmap(QtGui.QPixmap("msakni1.jpg"))
        self.photoButtuer.setScaledContents(True)
        self.photoButtuer.setObjectName("photoButtuer")
        self.label_170 = QtWidgets.QLabel(self.widgetBut)
        self.label_170.setGeometry(QtCore.QRect(30, 280, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setStyleSheet("border: 0px ")
        self.label_170.setObjectName("label_170")
        self.label_176 = QtWidgets.QLabel(self.widgetBut)
        self.label_176.setGeometry(QtCore.QRect(30, 300, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_176.setFont(font)
        self.label_176.setStyleSheet("border: 0px ")
        self.label_176.setObjectName("label_176")
        self.label_178 = QtWidgets.QLabel(self.widgetBut)
        self.label_178.setGeometry(QtCore.QRect(30, 320, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_178.setFont(font)
        self.label_178.setStyleSheet("border: 0px ")
        self.label_178.setObjectName("label_178")
        self.nomButteur = QtWidgets.QLabel(self.widgetBut)
        self.nomButteur.setGeometry(QtCore.QRect(100, 280, 59, 15))
        self.nomButteur.setStyleSheet("border: 0px ")
        self.nomButteur.setObjectName("nomButteur")
        self.prenomButteur = QtWidgets.QLabel(self.widgetBut)
        self.prenomButteur.setGeometry(QtCore.QRect(100, 300, 59, 15))
        self.prenomButteur.setStyleSheet("border: 0px ")
        self.prenomButteur.setObjectName("prenomButteur")
        self.equipeButteur = QtWidgets.QLabel(self.widgetBut)
        self.equipeButteur.setGeometry(QtCore.QRect(100, 320, 161, 16))
        self.equipeButteur.setStyleSheet("border: 0px ")
        self.equipeButteur.setObjectName("equipeButteur")
        self.numButLabel = QtWidgets.QLabel(self.widgetBut)
        self.numButLabel.setGeometry(QtCore.QRect(119, 28, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.numButLabel.setFont(font)
        self.numButLabel.setAutoFillBackground(False)
        self.numButLabel.setStyleSheet("border: 0px \n"
"")
        self.numButLabel.setObjectName("numButLabel")
        self.widgetGard = QtWidgets.QWidget(self.Statistique)
        self.widgetGard.setGeometry(QtCore.QRect(387, 160, 311, 371))
        self.widgetGard.setStyleSheet("border : 1px solid rgb(255, 252, 249)")
        self.widgetGard.setObjectName("widgetGard")
        self.label_189 = QtWidgets.QLabel(self.widgetGard)
        self.label_189.setGeometry(QtCore.QRect(80, 70, 161, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(19)
        self.label_189.setFont(font)
        self.label_189.setText("")
        self.label_189.setPixmap(QtGui.QPixmap("bolbol.jpg"))
        self.label_189.setScaledContents(True)
        self.label_189.setObjectName("label_189")
        self.equpeGardien = QtWidgets.QLabel(self.widgetGard)
        self.equpeGardien.setGeometry(QtCore.QRect(120, 320, 161, 16))
        self.equpeGardien.setStyleSheet("border: 0px ")
        self.equpeGardien.setObjectName("equpeGardien")
        self.nomGadien = QtWidgets.QLabel(self.widgetGard)
        self.nomGadien.setGeometry(QtCore.QRect(120, 280, 59, 15))
        self.nomGadien.setStyleSheet("border: 0px ")
        self.nomGadien.setObjectName("nomGadien")
        self.label_191 = QtWidgets.QLabel(self.widgetGard)
        self.label_191.setGeometry(QtCore.QRect(50, 320, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_191.setFont(font)
        self.label_191.setStyleSheet("border: 0px ")
        self.label_191.setObjectName("label_191")
        self.label_202 = QtWidgets.QLabel(self.widgetGard)
        self.label_202.setGeometry(QtCore.QRect(50, 280, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_202.setFont(font)
        self.label_202.setStyleSheet("border: 0px ")
        self.label_202.setObjectName("label_202")
        self.label_210 = QtWidgets.QLabel(self.widgetGard)
        self.label_210.setGeometry(QtCore.QRect(50, 300, 59, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_210.setFont(font)
        self.label_210.setStyleSheet("border: 0px ")
        self.label_210.setObjectName("label_210")
        self.prenomGardien = QtWidgets.QLabel(self.widgetGard)
        self.prenomGardien.setGeometry(QtCore.QRect(120, 300, 59, 15))
        self.prenomGardien.setStyleSheet("border: 0px ")
        self.prenomGardien.setObjectName("prenomGardien")
        self.numMatchGardien = QtWidgets.QLabel(self.widgetGard)
        self.numMatchGardien.setGeometry(QtCore.QRect(90, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.numMatchGardien.setFont(font)
        self.numMatchGardien.setAutoFillBackground(False)
        self.numMatchGardien.setStyleSheet("border: 0px \n"
"")
        self.numMatchGardien.setObjectName("numMatchGardien")
        self.widgetClass = QtWidgets.QWidget(self.Statistique)
        self.widgetClass.setGeometry(QtCore.QRect(730, 160, 311, 371))
        self.widgetClass.setStyleSheet("border : 1px solid rgb(255, 252, 249)")
        self.widgetClass.setObjectName("widgetClass")
        self.label_214 = QtWidgets.QLabel(self.widgetClass)
        self.label_214.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_214.setFont(font)
        self.label_214.setAutoFillBackground(False)
        self.label_214.setStyleSheet("border: 0px")
        self.label_214.setObjectName("label_214")
        self.label_219 = QtWidgets.QLabel(self.widgetClass)
        self.label_219.setGeometry(QtCore.QRect(20, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_219.setFont(font)
        self.label_219.setAutoFillBackground(False)
        self.label_219.setStyleSheet("border: 0px \n"
"")
        self.label_219.setObjectName("label_219")
        self.label_220 = QtWidgets.QLabel(self.widgetClass)
        self.label_220.setGeometry(QtCore.QRect(20, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_220.setFont(font)
        self.label_220.setAutoFillBackground(False)
        self.label_220.setStyleSheet("border: 0px \n"
"")
        self.label_220.setObjectName("label_220")
        self.ListeGroupA = QtWidgets.QListWidget(self.widgetClass)
        self.ListeGroupA.setGeometry(QtCore.QRect(20, 50, 271, 81))
        self.ListeGroupA.setStyleSheet("\n"
" border: 0px solid rgb(255, 255, 255)\n"
"")
        self.ListeGroupA.setObjectName("ListeGroupA")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(211, 212, 105))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.ListeGroupA.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupA.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupA.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupA.addItem(item)
        self.ListeGroupB = QtWidgets.QListWidget(self.widgetClass)
        self.ListeGroupB.setGeometry(QtCore.QRect(20, 160, 271, 81))
        self.ListeGroupB.setStyleSheet(" border: 0px solid rgb(255, 255, 255)\n"
"")
        self.ListeGroupB.setObjectName("ListeGroupB")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.ListeGroupB.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupB.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupB.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupB.addItem(item)
        self.ListeGroupC = QtWidgets.QListWidget(self.widgetClass)
        self.ListeGroupC.setGeometry(QtCore.QRect(20, 270, 271, 81))
        self.ListeGroupC.setStyleSheet("\n"
" border: 0px solid rgb(255, 255, 255)\n"
"")
        self.ListeGroupC.setObjectName("ListeGroupC")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.ListeGroupC.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupC.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupC.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ListeGroupC.addItem(item)
        self.labelMeiBut = QtWidgets.QLabel(self.Statistique)
        self.labelMeiBut.setGeometry(QtCore.QRect(80, 140, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(19)
        self.labelMeiBut.setFont(font)
        self.labelMeiBut.setObjectName("labelMeiBut")
        self.labelMeiGard = QtWidgets.QLabel(self.Statistique)
        self.labelMeiGard.setGeometry(QtCore.QRect(430, 140, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(19)
        self.labelMeiGard.setFont(font)
        self.labelMeiGard.setObjectName("labelMeiGard")
        self.labelClassement = QtWidgets.QLabel(self.Statistique)
        self.labelClassement.setGeometry(QtCore.QRect(800, 140, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(19)
        self.labelClassement.setFont(font)
        self.labelClassement.setStyleSheet("")
        self.labelClassement.setObjectName("labelClassement")
        self.widgetClass.raise_()
        self.widgetBut.raise_()
        self.labelStatistique.raise_()
        self.btnRetourStatic.raise_()
        self.label_263.raise_()
        self.widgetGard.raise_()
        self.labelMeiBut.raise_()
        self.labelMeiGard.raise_()
        self.labelClassement.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelStatistique.setText(_translate("Form", "Statistique"))
        self.label_170.setText(_translate("Form", "Nom "))
        self.label_176.setText(_translate("Form", "Prénom"))
        self.label_178.setText(_translate("Form", "Equipe"))
        self.nomButteur.setText(_translate("Form", "Youssef"))
        self.prenomButteur.setText(_translate("Form", "Msekni"))
        self.equipeButteur.setText(_translate("Form", "Espérance Tunisie"))
        self.numButLabel.setText(_translate("Form", "18 But"))
        self.equpeGardien.setText(_translate("Form", "Etoile Sportive Du Sahel"))
        self.nomGadien.setText(_translate("Form", "Aymen"))
        self.label_191.setText(_translate("Form", "Equipe"))
        self.label_202.setText(_translate("Form", "Nom "))
        self.label_210.setText(_translate("Form", "Prénom"))
        self.prenomGardien.setText(_translate("Form", "Balbouli"))
        self.numMatchGardien.setText(_translate("Form", "25 Match 0 but "))
        self.label_214.setText(_translate("Form", "Group A"))
        self.label_219.setText(_translate("Form", "Group B"))
        self.label_220.setText(_translate("Form", "Group C"))
        __sortingEnabled = self.ListeGroupA.isSortingEnabled()
        self.ListeGroupA.setSortingEnabled(False)
        item = self.ListeGroupA.item(0)
        item.setText(_translate("Form", "1)Etoile Sportive Du Sahel"))
        item = self.ListeGroupA.item(1)
        item.setText(_translate("Form", "2)Etoile Metlaoui"))
        item = self.ListeGroupA.item(2)
        item.setText(_translate("Form", "3)Club Africain"))
        item = self.ListeGroupA.item(3)
        item.setText(_translate("Form", "4)Club Sfaxien"))
        self.ListeGroupA.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.ListeGroupB.isSortingEnabled()
        self.ListeGroupB.setSortingEnabled(False)
        item = self.ListeGroupB.item(0)
        item.setText(_translate("Form", "1)Espérance Tunisie"))
        item = self.ListeGroupB.item(1)
        item.setText(_translate("Form", "4)Stade Gabesien"))
        item = self.ListeGroupB.item(2)
        item.setText(_translate("Form", "2)AS Bengerden"))
        item = self.ListeGroupB.item(3)
        item.setText(_translate("Form", "3)AS Marsa"))
        self.ListeGroupB.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.ListeGroupC.isSortingEnabled()
        self.ListeGroupC.setSortingEnabled(False)
        item = self.ListeGroupC.item(0)
        item.setText(_translate("Form", "1)Club Athletic Bizerte"))
        item = self.ListeGroupC.item(1)
        item.setText(_translate("Form", "2)Union Sportif Monastirienne"))
        item = self.ListeGroupC.item(2)
        item.setText(_translate("Form", "3)AS Gabes"))
        item = self.ListeGroupC.item(3)
        item.setText(_translate("Form", "4)Stade Tunisien"))
        self.ListeGroupC.setSortingEnabled(__sortingEnabled)
        self.labelMeiBut.setText(_translate("Form", "Meuilleur butteur"))
        self.labelMeiGard.setText(_translate("Form", "Meuilleur gardien"))
        self.labelClassement.setText(_translate("Form", "Classement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

