# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equipe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMessageBox


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1100, 600)
        widget.setStyleSheet("background-color : #2d2d2d;\n"
"color : #b5b5b5")
        self.Equipe = QtWidgets.QWidget(widget)
        self.Equipe.setEnabled(True)
        self.Equipe.setGeometry(QtCore.QRect(0, 0, 1100, 601))
        self.Equipe.setStyleSheet("")
        self.Equipe.setObjectName("Equipe")
        self.labelListEquip = QtWidgets.QLabel(self.Equipe)
        self.labelListEquip.setGeometry(QtCore.QRect(75, 40, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(36)
        self.labelListEquip.setFont(font)
        self.labelListEquip.setObjectName("labelListEquip")
        self.btnRetour_4 = QtWidgets.QToolButton(self.Equipe)
        self.btnRetour_4.setGeometry(QtCore.QRect(20, 550, 41, 30))
        self.btnRetour_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRetour_4.setStyleSheet("border:none")
        self.btnRetour_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("retour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRetour_4.setIcon(icon)
        self.btnRetour_4.setIconSize(QtCore.QSize(30, 30))
        self.btnRetour_4.setObjectName("btnRetour_4")
        self.label_171 = QtWidgets.QLabel(self.Equipe)
        self.label_171.setGeometry(QtCore.QRect(25, 46, 40, 40))
        self.label_171.setText("")
        self.label_171.setPixmap(QtGui.QPixmap("entreneur.png"))
        self.label_171.setScaledContents(True)
        self.label_171.setObjectName("label_171")
        self.AjoutEquipe = QtWidgets.QWidget(self.Equipe)
        self.AjoutEquipe.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.AjoutEquipe.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.AjoutEquipe.setObjectName("AjoutEquipe")
        self.ajouterEquipe = QtWidgets.QWidget(self.AjoutEquipe)
        self.ajouterEquipe.setGeometry(QtCore.QRect(220, 120, 671, 341))
        self.ajouterEquipe.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.ajouterEquipe.setObjectName("ajouterEquipe")
        self.labelNouvEquipe = QtWidgets.QLabel(self.ajouterEquipe)
        self.labelNouvEquipe.setGeometry(QtCore.QRect(50, 14, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.labelNouvEquipe.setFont(font)
        self.labelNouvEquipe.setObjectName("labelNouvEquipe")
        self.label_173 = QtWidgets.QLabel(self.ajouterEquipe)
        self.label_173.setGeometry(QtCore.QRect(13, 16, 31, 31))
        self.label_173.setText("")
        self.label_173.setPixmap(QtGui.QPixmap("add.png"))
        self.label_173.setScaledContents(True)
        self.label_173.setObjectName("label_173")
        self.label_174 = QtWidgets.QLabel(self.ajouterEquipe)
        self.label_174.setGeometry(QtCore.QRect(290, 100, 31, 16))
        self.label_174.setObjectName("label_174")
        self.ajouNomEquipe = QtWidgets.QLineEdit(self.ajouterEquipe)
        self.ajouNomEquipe.setGeometry(QtCore.QRect(292, 120, 291, 31))
        self.ajouNomEquipe.setStyleSheet("border:1px solid gray")
        self.ajouNomEquipe.setObjectName("ajouNomEquipe")
        self.ajoutPhotoEquipe = QtWidgets.QLabel(self.ajouterEquipe)
        self.ajoutPhotoEquipe.setGeometry(QtCore.QRect(90, 80, 151, 161))
        self.ajoutPhotoEquipe.setText("")
        self.ajoutPhotoEquipe.setPixmap(QtGui.QPixmap("user.png"))
        self.ajoutPhotoEquipe.setScaledContents(True)
        self.ajoutPhotoEquipe.setObjectName("ajoutPhotoEquipe")
        self.btnUplodEquipe = QtWidgets.QToolButton(self.ajouterEquipe)
        self.btnUplodEquipe.setGeometry(QtCore.QRect(100, 250, 111, 21))
        self.btnUplodEquipe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUplodEquipe.setIcon(icon1)
        self.btnUplodEquipe.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnUplodEquipe.setObjectName("btnUplodEquipe")
        self.btnAnnuleEquip = QtWidgets.QToolButton(self.ajouterEquipe)
        self.btnAnnuleEquip.setGeometry(QtCore.QRect(610, 300, 31, 31))
        self.btnAnnuleEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnnuleEquip.setIcon(icon2)
        self.btnAnnuleEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnuleEquip.setObjectName("btnAnnuleEquip")
        self.btnEnregEquipe = QtWidgets.QToolButton(self.ajouterEquipe)
        self.btnEnregEquipe.setGeometry(QtCore.QRect(570, 300, 31, 31))
        self.btnEnregEquipe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEnregEquipe.setIcon(icon3)
        self.btnEnregEquipe.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregEquipe.setObjectName("btnEnregEquipe")
        self.ajouLocalEquipe = QtWidgets.QLineEdit(self.ajouterEquipe)
        self.ajouLocalEquipe.setGeometry(QtCore.QRect(291, 180, 291, 31))
        self.ajouLocalEquipe.setStyleSheet("border:1px solid gray")
        self.ajouLocalEquipe.setText("")
        self.ajouLocalEquipe.setObjectName("ajouLocalEquipe")
        self.label_177 = QtWidgets.QLabel(self.ajouterEquipe)
        self.label_177.setGeometry(QtCore.QRect(290, 160, 71, 16))
        self.label_177.setObjectName("label_177")
        self.labelNouvEquipe.raise_()
        self.label_173.raise_()
        self.label_174.raise_()
        self.ajouNomEquipe.raise_()
        self.ajoutPhotoEquipe.raise_()
        self.btnUplodEquipe.raise_()
        self.ajouLocalEquipe.raise_()
        self.label_177.raise_()
        self.btnEnregEquipe.raise_()
        self.btnAnnuleEquip.raise_()
        self.ModifEquipe = QtWidgets.QWidget(self.Equipe)
        self.ModifEquipe.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.ModifEquipe.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.ModifEquipe.setObjectName("ModifEquipe")
        self.modifEquip = QtWidgets.QWidget(self.ModifEquipe)
        self.modifEquip.setGeometry(QtCore.QRect(220, 110, 681, 371))
        self.modifEquip.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.modifEquip.setObjectName("modifEquip")
        self.labelModifEquip = QtWidgets.QLabel(self.modifEquip)
        self.labelModifEquip.setGeometry(QtCore.QRect(50, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.labelModifEquip.setFont(font)
        self.labelModifEquip.setObjectName("labelModifEquip")
        self.label_183 = QtWidgets.QLabel(self.modifEquip)
        self.label_183.setGeometry(QtCore.QRect(13, 16, 31, 31))
        self.label_183.setText("")
        self.label_183.setPixmap(QtGui.QPixmap("modif.png"))
        self.label_183.setScaledContents(True)
        self.label_183.setObjectName("label_183")
        self.label_184 = QtWidgets.QLabel(self.modifEquip)
        self.label_184.setGeometry(QtCore.QRect(290, 90, 31, 16))
        self.label_184.setObjectName("label_184")
        self.modifNomEquip = QtWidgets.QLineEdit(self.modifEquip)
        self.modifNomEquip.setGeometry(QtCore.QRect(292, 110, 291, 31))
        self.modifNomEquip.setStyleSheet("border:1px solid gray")
        self.modifNomEquip.setObjectName("modifNomEquip")
        self.modifLocalEquip = QtWidgets.QLineEdit(self.modifEquip)
        self.modifLocalEquip.setGeometry(QtCore.QRect(290, 170, 291, 31))
        self.modifLocalEquip.setStyleSheet("border:1px solid gray")
        self.modifLocalEquip.setObjectName("modifLocalEquip")
        self.label_188 = QtWidgets.QLabel(self.modifEquip)
        self.label_188.setGeometry(QtCore.QRect(290, 150, 71, 16))
        self.label_188.setObjectName("label_188")
        self.modifPhotoEquip = QtWidgets.QLabel(self.modifEquip)
        self.modifPhotoEquip.setGeometry(QtCore.QRect(90, 80, 151, 161))
        self.modifPhotoEquip.setText("")
        self.modifPhotoEquip.setPixmap(QtGui.QPixmap("img/eqp/ess.png"))
        self.modifPhotoEquip.setScaledContents(True)
        self.modifPhotoEquip.setObjectName("modifPhotoEquip")
        self.btnModifUplodEquipe = QtWidgets.QToolButton(self.modifEquip)
        self.btnModifUplodEquipe.setGeometry(QtCore.QRect(120, 250, 111, 21))
        self.btnModifUplodEquipe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModifUplodEquipe.setIcon(icon1)
        self.btnModifUplodEquipe.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnModifUplodEquipe.setObjectName("btnModifUplodEquipe")
        self.btnModifAnnuleEquip = QtWidgets.QToolButton(self.modifEquip)
        self.btnModifAnnuleEquip.setGeometry(QtCore.QRect(570, 420, 31, 31))
        self.btnModifAnnuleEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/closecircularbutton_79562 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModifAnnuleEquip.setIcon(icon4)
        self.btnModifAnnuleEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnModifAnnuleEquip.setObjectName("btnModifAnnuleEquip")
        self.btnModifEnregEquip = QtWidgets.QToolButton(self.modifEquip)
        self.btnModifEnregEquip.setGeometry(QtCore.QRect(620, 420, 31, 31))
        self.btnModifEnregEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/closecircularbutton_79562 (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModifEnregEquip.setIcon(icon5)
        self.btnModifEnregEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnModifEnregEquip.setObjectName("btnModifEnregEquip")
        self.btnEnregEquipe_2 = QtWidgets.QToolButton(self.modifEquip)
        self.btnEnregEquipe_2.setGeometry(QtCore.QRect(580, 320, 31, 31))
        self.btnEnregEquipe_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEnregEquipe_2.setIcon(icon3)
        self.btnEnregEquipe_2.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregEquipe_2.setObjectName("btnEnregEquipe_2")
        self.btnAnnuleEquip_2 = QtWidgets.QToolButton(self.modifEquip)
        self.btnAnnuleEquip_2.setGeometry(QtCore.QRect(620, 320, 31, 31))
        self.btnAnnuleEquip_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAnnuleEquip_2.setIcon(icon2)
        self.btnAnnuleEquip_2.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnuleEquip_2.setObjectName("btnAnnuleEquip_2")
        self.SupprimerEquip = QtWidgets.QWidget(self.Equipe)
        self.SupprimerEquip.setGeometry(QtCore.QRect(0, 700, 1111, 611))
        self.SupprimerEquip.setStyleSheet("background-color:rgba(0,0,0,0.7)")
        self.SupprimerEquip.setObjectName("SupprimerEquip")
        self.SuppEquip = QtWidgets.QWidget(self.SupprimerEquip)
        self.SuppEquip.setGeometry(QtCore.QRect(-20, 240, 1131, 141))
        self.SuppEquip.setStyleSheet("background-color : #2d2d2d;\n"
"border-radius:20px\n"
"")
        self.SuppEquip.setObjectName("SuppEquip")
        self.label_192 = QtWidgets.QLabel(self.SuppEquip)
        self.label_192.setGeometry(QtCore.QRect(160, 34, 791, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        self.label_192.setFont(font)
        self.label_192.setObjectName("label_192")
        self.label_193 = QtWidgets.QLabel(self.SuppEquip)
        self.label_193.setGeometry(QtCore.QRect(110, 40, 41, 41))
        self.label_193.setText("")
        self.label_193.setPixmap(QtGui.QPixmap("supp.png"))
        self.label_193.setScaledContents(True)
        self.label_193.setObjectName("label_193")
        self.btnSuppAnnuleEquip = QtWidgets.QToolButton(self.SuppEquip)
        self.btnSuppAnnuleEquip.setGeometry(QtCore.QRect(530, 100, 31, 31))
        self.btnSuppAnnuleEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSuppAnnuleEquip.setIcon(icon4)
        self.btnSuppAnnuleEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnSuppAnnuleEquip.setObjectName("btnSuppAnnuleEquip")
        self.btnEnregEquipe_3 = QtWidgets.QToolButton(self.SuppEquip)
        self.btnEnregEquipe_3.setGeometry(QtCore.QRect(490, 90, 31, 31))
        self.btnEnregEquipe_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEnregEquipe_3.setIcon(icon3)
        self.btnEnregEquipe_3.setIconSize(QtCore.QSize(30, 30))
        self.btnEnregEquipe_3.setObjectName("btnEnregEquipe_3")
        self.btnAnnuleEquip_3 = QtWidgets.QToolButton(self.SuppEquip)
        self.btnAnnuleEquip_3.setGeometry(QtCore.QRect(530, 90, 31, 31))
        self.btnAnnuleEquip_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAnnuleEquip_3.setIcon(icon2)
        self.btnAnnuleEquip_3.setIconSize(QtCore.QSize(30, 30))
        self.btnAnnuleEquip_3.setObjectName("btnAnnuleEquip_3")
        self.listEquipe = QtWidgets.QListWidget(self.Equipe)
        self.listEquipe.setGeometry(QtCore.QRect(30, 160, 431, 381))
        self.listEquipe.setStyleSheet("\n"
" border: 1px solid ;\n"
"border-color:#b5b5b5;\n"
"")
        self.listEquipe.setObjectName("listEquipe")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/eqp/ess.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listEquipe.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/eqp/EST.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listEquipe.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/eqp/CA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listEquipe.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/eqp/AHLY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listEquipe.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/eqp/Logo_Zamalek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.listEquipe.addItem(item)
        self.FicheEquip = QtWidgets.QFrame(self.Equipe)
        self.FicheEquip.setGeometry(QtCore.QRect(540, 130, 491, 411))
        self.FicheEquip.setStyleSheet("QFrame{ border: 1px solid; border-color:#b5b5b5;}")
        self.FicheEquip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FicheEquip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FicheEquip.setObjectName("FicheEquip")
        self.PhotoEquip = QtWidgets.QLabel(self.FicheEquip)
        self.PhotoEquip.setEnabled(True)
        self.PhotoEquip.setGeometry(QtCore.QRect(30, 20, 50, 50))
        self.PhotoEquip.setMaximumSize(QtCore.QSize(50, 50))
        self.PhotoEquip.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.PhotoEquip.setText("")
        self.PhotoEquip.setPixmap(QtGui.QPixmap("img/eqp/ess.png"))
        self.PhotoEquip.setScaledContents(True)
        self.PhotoEquip.setObjectName("PhotoEquip")
        self.starFull = QtWidgets.QLabel(self.FicheEquip)
        self.starFull.setEnabled(True)
        self.starFull.setGeometry(QtCore.QRect(110, 40, 21, 21))
        self.starFull.setMaximumSize(QtCore.QSize(50, 50))
        self.starFull.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.starFull.setText("")
        self.starFull.setPixmap(QtGui.QPixmap("img/star.png"))
        self.starFull.setScaledContents(True)
        self.starFull.setObjectName("starFull")
        self.starEmpt = QtWidgets.QLabel(self.FicheEquip)
        self.starEmpt.setEnabled(True)
        self.starEmpt.setGeometry(QtCore.QRect(130, 40, 21, 21))
        self.starEmpt.setMaximumSize(QtCore.QSize(50, 50))
        self.starEmpt.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.starEmpt.setText("")
        self.starEmpt.setPixmap(QtGui.QPixmap("img/emptyStar.png"))
        self.starEmpt.setScaledContents(True)
        self.starEmpt.setObjectName("starEmpt")
        self.starEmpt_2 = QtWidgets.QLabel(self.FicheEquip)
        self.starEmpt_2.setEnabled(True)
        self.starEmpt_2.setGeometry(QtCore.QRect(150, 40, 21, 21))
        self.starEmpt_2.setMaximumSize(QtCore.QSize(50, 50))
        self.starEmpt_2.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.starEmpt_2.setText("")
        self.starEmpt_2.setPixmap(QtGui.QPixmap("img/emptyStar.png"))
        self.starEmpt_2.setScaledContents(True)
        self.starEmpt_2.setObjectName("starEmpt_2")
        self.starEmpt_3 = QtWidgets.QLabel(self.FicheEquip)
        self.starEmpt_3.setEnabled(True)
        self.starEmpt_3.setGeometry(QtCore.QRect(170, 40, 21, 21))
        self.starEmpt_3.setMaximumSize(QtCore.QSize(50, 50))
        self.starEmpt_3.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.starEmpt_3.setText("")
        self.starEmpt_3.setPixmap(QtGui.QPixmap("img/emptyStar.png"))
        self.starEmpt_3.setScaledContents(True)
        self.starEmpt_3.setObjectName("starEmpt_3")
        self.label_73 = QtWidgets.QLabel(self.FicheEquip)
        self.label_73.setGeometry(QtCore.QRect(110, 10, 161, 31))
        self.label_73.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.FicheEquip)
        self.label_74.setGeometry(QtCore.QRect(10, 70, 161, 41))
        self.label_74.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.FicheEquip)
        self.label_75.setGeometry(QtCore.QRect(10, 130, 161, 31))
        self.label_75.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_75.setObjectName("label_75")
        self.idEquip = QtWidgets.QLabel(self.FicheEquip)
        self.idEquip.setGeometry(QtCore.QRect(100, 70, 161, 41))
        self.idEquip.setStyleSheet("QLabel{\n"
" color:rgb(255, 255, 255);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.idEquip.setObjectName("idEquip")
        self.localEquip = QtWidgets.QLabel(self.FicheEquip)
        self.localEquip.setGeometry(QtCore.QRect(100, 130, 161, 31))
        self.localEquip.setStyleSheet("QLabel{\n"
" color: rgb(255, 255, 255);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.localEquip.setObjectName("localEquip")
        self.line_8 = QtWidgets.QFrame(self.FicheEquip)
        self.line_8.setGeometry(QtCore.QRect(10, 170, 469, 1))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setStyleSheet("QLine {\n"
"\n"
" border: 0px  tranparent\n"
"}")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_165 = QtWidgets.QLabel(self.FicheEquip)
        self.label_165.setGeometry(QtCore.QRect(10, 100, 161, 41))
        self.label_165.setStyleSheet("QLabel{\n"
" color: rgb(248, 255, 239);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.label_165.setObjectName("label_165")
        self.entraineurEquip = QtWidgets.QLabel(self.FicheEquip)
        self.entraineurEquip.setGeometry(QtCore.QRect(100, 100, 161, 41))
        self.entraineurEquip.setStyleSheet("QLabel{\n"
" color:rgb(255, 255, 255);\n"
" border: 0px  tranparent;\n"
"\n"
"}")
        self.entraineurEquip.setObjectName("entraineurEquip")
        self.btnChangeJr = QtWidgets.QToolButton(self.FicheEquip)
        self.btnChangeJr.setGeometry(QtCore.QRect(10, 172, 28, 22))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("stck (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChangeJr.setIcon(icon11)
        self.btnChangeJr.setObjectName("btnChangeJr")
        self.tableJoueur = QtWidgets.QTableWidget(self.FicheEquip)
        self.tableJoueur.setGeometry(QtCore.QRect(10, 200, 471, 171))
        font = QtGui.QFont()
        font.setFamily("Samyak Malayalam")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableJoueur.setFont(font)
        self.tableJoueur.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableJoueur.setAutoFillBackground(False)
        self.tableJoueur.setStyleSheet("QTableView{\n"
"\n"
"\n"
" border: 1px solid rgb(255, 252, 249)}\n"
"")
        self.tableJoueur.setAutoScrollMargin(10)
        self.tableJoueur.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableJoueur.setIconSize(QtCore.QSize(8, 8))
        self.tableJoueur.setRowCount(3)
        self.tableJoueur.setObjectName("tableJoueur")
        self.tableJoueur.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../projetQt/img/eqp/unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon12)
        self.tableJoueur.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../projetQt/img/eqp/ammar.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon13)
        self.tableJoueur.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../projetQt/img/eqp/bbb9.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon14)
        self.tableJoueur.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableJoueur.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableJoueur.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableJoueur.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJoueur.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableJoueur.setItem(2, 2, item)
        self.btnChangeJr_2 = QtWidgets.QToolButton(self.FicheEquip)
        self.btnChangeJr_2.setGeometry(QtCore.QRect(40, 172, 28, 22))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("stck (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChangeJr_2.setIcon(icon15)
        self.btnChangeJr_2.setObjectName("btnChangeJr_2")
        self.tableMatchEquip = QtWidgets.QTableWidget(self.FicheEquip)
        self.tableMatchEquip.setGeometry(QtCore.QRect(10, 200, 471, 171))
        font = QtGui.QFont()
        font.setFamily("Samyak Malayalam")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableMatchEquip.setFont(font)
        self.tableMatchEquip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableMatchEquip.setAutoFillBackground(False)
        self.tableMatchEquip.setStyleSheet("QTableView{\n"
"\n"
"\n"
" border: 1px solid rgb(255, 252, 249)}\n"
"")
        self.tableMatchEquip.setAutoScrollMargin(10)
        self.tableMatchEquip.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableMatchEquip.setIconSize(QtCore.QSize(8, 8))
        self.tableMatchEquip.setRowCount(2)
        self.tableMatchEquip.setObjectName("tableMatchEquip")
        self.tableMatchEquip.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableMatchEquip.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMatchEquip.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMatchEquip.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMatchEquip.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMatchEquip.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon7)
        self.tableMatchEquip.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon6)
        self.tableMatchEquip.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMatchEquip.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon6)
        self.tableMatchEquip.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon7)
        self.tableMatchEquip.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMatchEquip.setItem(1, 2, item)
        self.tableMatchEquip.horizontalHeader().setDefaultSectionSize(127)
        self.tableMatchEquip.horizontalHeader().setStretchLastSection(False)
        self.tableMatchEquip.verticalHeader().setDefaultSectionSize(33)
        self.tableMatchEquip.verticalHeader().setMinimumSectionSize(0)
        self.txtRechEquip = QtWidgets.QLineEdit(self.Equipe)
        self.txtRechEquip.setGeometry(QtCore.QRect(30, 130, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtRechEquip.setFont(font)
        self.txtRechEquip.setStyleSheet("border : 1px groove;border-color:#b5b5b5;color:white")
        self.txtRechEquip.setObjectName("txtRechEquip")
        self.label_163 = QtWidgets.QLabel(self.Equipe)
        self.label_163.setGeometry(QtCore.QRect(434, 135, 20, 20))
        self.label_163.setText("")
        self.label_163.setPixmap(QtGui.QPixmap("cherche.png"))
        self.label_163.setScaledContents(True)
        self.label_163.setObjectName("label_163")
        self.label_164 = QtWidgets.QLabel(self.Equipe)
        self.label_164.setGeometry(QtCore.QRect(560, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(False)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.btnAjout_2 = QtWidgets.QToolButton(self.Equipe)
        self.btnAjout_2.setGeometry(QtCore.QRect(1390, -200, 31, 31))
        self.btnAjout_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAjout_2.setStyleSheet("border:none")
        self.btnAjout_2.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAjout_2.setIcon(icon16)
        self.btnAjout_2.setIconSize(QtCore.QSize(30, 30))
        self.btnAjout_2.setObjectName("btnAjout_2")
        self.btnModif_2 = QtWidgets.QToolButton(self.Equipe)
        self.btnModif_2.setGeometry(QtCore.QRect(1440, -200, 31, 31))
        self.btnModif_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModif_2.setStyleSheet("border:none")
        self.btnModif_2.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("modif.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModif_2.setIcon(icon17)
        self.btnModif_2.setIconSize(QtCore.QSize(30, 30))
        self.btnModif_2.setObjectName("btnModif_2")
        self.btnAjoutEquip = QtWidgets.QToolButton(self.Equipe)
        self.btnAjoutEquip.setGeometry(QtCore.QRect(890, 50, 31, 31))
        self.btnAjoutEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAjoutEquip.setStyleSheet("border:none")
        self.btnAjoutEquip.setText("")
        self.btnAjoutEquip.setIcon(icon16)
        self.btnAjoutEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnAjoutEquip.setObjectName("btnAjoutEquip")
        self.btnModifEquip = QtWidgets.QToolButton(self.Equipe)
        self.btnModifEquip.setGeometry(QtCore.QRect(940, 50, 31, 31))
        self.btnModifEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnModifEquip.setStyleSheet("border:none")
        self.btnModifEquip.setText("")
        self.btnModifEquip.setIcon(icon17)
        self.btnModifEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnModifEquip.setObjectName("btnModifEquip")
        self.btnSuppEquip = QtWidgets.QToolButton(self.Equipe)
        self.btnSuppEquip.setGeometry(QtCore.QRect(990, 50, 31, 31))
        self.btnSuppEquip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSuppEquip.setStyleSheet("border:none")
        self.btnSuppEquip.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("supp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuppEquip.setIcon(icon18)
        self.btnSuppEquip.setIconSize(QtCore.QSize(30, 30))
        self.btnSuppEquip.setObjectName("btnSuppEquip")
        self.FicheEquip.raise_()
        self.btnSuppEquip.raise_()
        self.btnModifEquip.raise_()
        self.btnAjoutEquip.raise_()
        self.label_164.raise_()
        self.txtRechEquip.raise_()
        self.label_163.raise_()
        self.listEquipe.raise_()
        self.labelListEquip.raise_()
        self.btnRetour_4.raise_()
        self.label_171.raise_()
        self.AjoutEquipe.raise_()
        self.SupprimerEquip.raise_()
        self.btnAjout_2.raise_()
        self.btnModif_2.raise_()
        self.ModifEquipe.raise_()

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.labelListEquip.setText(_translate("widget", "Liste Des Equipes"))
        self.labelNouvEquipe.setText(_translate("widget", "Nouvelle Equipe"))
        self.label_174.setText(_translate("widget", "Nom"))
        self.ajouNomEquipe.setPlaceholderText(_translate("widget", "Ex : ESS"))
        self.btnUplodEquipe.setText(_translate("widget", " Upload photo"))
        self.btnAnnuleEquip.setText(_translate("widget", "..."))
        self.btnEnregEquipe.setText(_translate("widget", "..."))
        self.ajouLocalEquipe.setPlaceholderText(_translate("widget", "Ex : Sousse"))
        self.label_177.setText(_translate("widget", "Localisation"))
        self.labelModifEquip.setText(_translate("widget", "Modifier Equipe"))
        self.label_184.setText(_translate("widget", "Nom"))
        self.modifNomEquip.setText(_translate("widget", "Etoile Sportive Du Sahel"))
        self.modifNomEquip.setPlaceholderText(_translate("widget", "Ex : Msekni"))
        self.modifLocalEquip.setText(_translate("widget", "Sousse"))
        self.modifLocalEquip.setPlaceholderText(_translate("widget", "Ex : Tunisien"))
        self.label_188.setText(_translate("widget", "Localisation"))
        self.btnModifUplodEquipe.setText(_translate("widget", " Upload photo"))
        self.btnModifAnnuleEquip.setText(_translate("widget", "..."))
        self.btnModifEnregEquip.setText(_translate("widget", "..."))
        self.btnEnregEquipe_2.setText(_translate("widget", "..."))
        self.btnAnnuleEquip_2.setText(_translate("widget", "..."))
        self.label_192.setText(_translate("widget", "Voulez vous vraiment supprimer cette equipe ?"))
        self.btnSuppAnnuleEquip.setText(_translate("widget", "..."))
        self.btnEnregEquipe_3.setText(_translate("widget", "..."))
        self.btnAnnuleEquip_3.setText(_translate("widget", "..."))
        __sortingEnabled = self.listEquipe.isSortingEnabled()
        self.listEquipe.setSortingEnabled(False)
        item = self.listEquipe.item(0)
        item.setText(_translate("widget", "Etoile Sportive Du Sahel"))
        item = self.listEquipe.item(1)
        item.setText(_translate("widget", "Espérance Tunisie"))
        item = self.listEquipe.item(2)
        item.setText(_translate("widget", "Club Africain"))
        item = self.listEquipe.item(3)
        item.setText(_translate("widget", "Al Ahly Fc"))
        item = self.listEquipe.item(4)
        item.setText(_translate("widget", "Al Zamalek Fc"))
        self.listEquipe.setSortingEnabled(__sortingEnabled)
        self.label_73.setText(_translate("widget", "Etoile Sportive Du Sahel"))
        self.label_74.setText(_translate("widget", "ID"))
        self.label_75.setText(_translate("widget", "Localisation"))
        self.idEquip.setText(_translate("widget", "1925ESS"))
        self.localEquip.setText(_translate("widget", "Sousse"))
        self.label_165.setText(_translate("widget", "Entraîneur "))
        self.entraineurEquip.setText(_translate("widget", "Imed Ben Younes"))
        self.btnChangeJr.setText(_translate("widget", "Joueur"))
        item = self.tableJoueur.verticalHeaderItem(0)
        item.setText(_translate("widget", "Amine Ben Amor 29"))
        item = self.tableJoueur.verticalHeaderItem(1)
        item.setText(_translate("widget", "Ammar Jemal 05"))
        item = self.tableJoueur.verticalHeaderItem(2)
        item.setText(_translate("widget", "Baghded Bounjeh 09"))
        item = self.tableJoueur.horizontalHeaderItem(0)
        item.setText(_translate("widget", "NbMatch"))
        item = self.tableJoueur.horizontalHeaderItem(1)
        item.setText(_translate("widget", "NbBut"))
        item = self.tableJoueur.horizontalHeaderItem(2)
        item.setText(_translate("widget", "Poste"))
        __sortingEnabled = self.tableJoueur.isSortingEnabled()
        self.tableJoueur.setSortingEnabled(False)
        item = self.tableJoueur.item(0, 0)
        item.setText(_translate("widget", "119"))
        item = self.tableJoueur.item(0, 1)
        item.setText(_translate("widget", "3"))
        item = self.tableJoueur.item(0, 2)
        item.setText(_translate("widget", "Milieux Défesif"))
        item = self.tableJoueur.item(1, 0)
        item.setText(_translate("widget", "209"))
        item = self.tableJoueur.item(1, 1)
        item.setText(_translate("widget", "25"))
        item = self.tableJoueur.item(1, 2)
        item.setText(_translate("widget", "Défenseur central"))
        item = self.tableJoueur.item(2, 0)
        item.setText(_translate("widget", "74"))
        item = self.tableJoueur.item(2, 1)
        item.setText(_translate("widget", "46"))
        item = self.tableJoueur.item(2, 2)
        item.setText(_translate("widget", "Avant-centre"))
        self.tableJoueur.setSortingEnabled(__sortingEnabled)
        self.btnChangeJr_2.setText(_translate("widget", "..."))
        item = self.tableMatchEquip.verticalHeaderItem(0)
        item.setText(_translate("widget", "01/02/2021"))
        item = self.tableMatchEquip.verticalHeaderItem(1)
        item.setText(_translate("widget", "11/02/2021"))
        item = self.tableMatchEquip.horizontalHeaderItem(0)
        item.setText(_translate("widget", "Equipe Local "))
        item = self.tableMatchEquip.horizontalHeaderItem(1)
        item.setText(_translate("widget", "Equipe Extérieur"))
        item = self.tableMatchEquip.horizontalHeaderItem(2)
        item.setText(_translate("widget", "Score"))
        __sortingEnabled = self.tableMatchEquip.isSortingEnabled()
        self.tableMatchEquip.setSortingEnabled(False)
        item = self.tableMatchEquip.item(0, 0)
        item.setText(_translate("widget", "EST"))
        item = self.tableMatchEquip.item(0, 1)
        item.setText(_translate("widget", "ESS"))
        item = self.tableMatchEquip.item(0, 2)
        item.setText(_translate("widget", "0-0"))
        item = self.tableMatchEquip.item(1, 0)
        item.setText(_translate("widget", "ESS"))
        item = self.tableMatchEquip.item(1, 1)
        item.setText(_translate("widget", "EST"))
        item = self.tableMatchEquip.item(1, 2)
        item.setText(_translate("widget", "0-0"))
        self.tableMatchEquip.setSortingEnabled(__sortingEnabled)
        self.txtRechEquip.setPlaceholderText(_translate("widget", "Chercher par nom"))
        self.label_164.setText(_translate("widget", "Fiche Equipe"))
        # Crud Equipe
        self.btnAjoutEquip.clicked.connect(lambda:self.AjoutEquipe.setGeometry(QtCore.QRect(0, 0, 1111, 611)))
        self.btnAnnuleEquip.clicked.connect(lambda:self.AjoutEquipe.setGeometry(QtCore.QRect(0, 700, 1111, 611)))
        self.btnEnregEquipe.clicked.connect(self.validateEquipe)
        self.btnModifEquip.clicked.connect(lambda:self.ModifEquipe.setGeometry(QtCore.QRect(0, 0, 1111, 611)))
        self.btnEnregEquipe_2.clicked.connect(self.validateEquipe)
        self.btnAnnuleEquip_2.clicked.connect(lambda:self.ModifEquipe.setGeometry(QtCore.QRect(0, 700, 1111, 611)))
        self.btnSuppEquip.clicked.connect(lambda:self.SupprimerEquip.setGeometry(QtCore.QRect(0, 0, 1111, 611)))
        self.btnAnnuleEquip_3.clicked.connect(lambda:self.SupprimerEquip.setGeometry(QtCore.QRect(0, 700, 1111, 611)))
        self.btnChangeJr_2.clicked.connect(self.tabJr)
        self.btnChangeJr.clicked.connect(self.tabCal)

    # nav entre les deux tableaux

    def tabJr(self):
        self.tableMatchEquip.hide()
        self.tableJoueur.show()
    def tabCal(self):
        self.tableMatchEquip.show()
        self.tableJoueur.hide()

    # verification et controle de saisie

    def show_popupID(self):
        msg = QMessageBox()
        msg.setWindowTitle("ERROR")
        msg.setText("Veuillez verifier l'identifiant !")
        msg.setIcon(QMessageBox.Warning)
        msg.setWindowFlags(Qt.FramelessWindowHint | Qt.Dialog)

        msg.exec_()
    def show_popupNom(self):
        msg1 = QMessageBox()
        msg1.setWindowTitle("ERROR")
        msg1.setText("Veuillez verifier le nom !")
        msg1.setIcon(QMessageBox.Warning)
        msg1.setWindowFlags(Qt.FramelessWindowHint | Qt.Dialog)

        msg1.exec_()
    def show_popupLocal(self):
        msg = QMessageBox()
        msg.setWindowTitle("ERROR")
        msg.setText("Le champ local ne doit pas être vide !")
        msg.setIcon(QMessageBox.Warning)
        msg.setWindowFlags(Qt.FramelessWindowHint | Qt.Dialog)

        msg.exec_()

    def validateEquipe(self):

        if self.ajouNomEquipe.text() == "" or self.modifNomEquip.text()== "":
            self.show_popupNom()
        elif self.ajouLocalEquipe.text() == "" or self.modifLocalEquip.text()== "":
            self.show_popupLocal()
        else:
            print("DB  Equip")
